version: '3.8'
services:
  server:
    build:
      dockerfile: ./Dockerfile
    ports: 
      - "3000:3000"
    depends_on:
      - database # same as -l (link)
  database:
    image: 'postgres:11-alpine'
    environment:
      POSTGRES_PASSWORD: 'password'

